name: Push to Docker Hub

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.WORKFLOW_GIT_ACCESS_TOKEN }}

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: joshuasundance
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      run: |
        docker build \
          -t joshuasundance/langchain-research-assistant-docker:${{ github.ref_name }} \
          -t joshuasundance/langchain-research-assistant-docker:latest \
          .

    - name: Push to Docker Hub
      run: docker push -a joshuasundance/langchain-research-assistant-docker
